# Generated by Django 4.2.28 on 2026-03-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('query_desc', models.CharField(blank=True, max_length=255)),
                ('results_json', models.JSONField(default=list)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
