# Generated by GPT-5.2 on 2026-03-17

from django.db import migrations


def _table_exists(schema_editor, table_name: str) -> bool:
    return table_name in schema_editor.connection.introspection.table_names()


def ensure_joblistingcache_table(apps, schema_editor):
    JobListingCache = apps.get_model("jobs", "JobListingCache")
    table = JobListingCache._meta.db_table
    if not _table_exists(schema_editor, table):
        schema_editor.create_model(JobListingCache)


def reverse_ensure_joblistingcache_table(apps, schema_editor):
    JobListingCache = apps.get_model("jobs", "JobListingCache")
    table = JobListingCache._meta.db_table
    if _table_exists(schema_editor, table):
        schema_editor.delete_model(JobListingCache)


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            ensure_joblistingcache_table,
            reverse_ensure_joblistingcache_table,
        ),
    ]

