# Generated by Django 4.2.28 on 2026-03-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='major_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='min_salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_job_type',
            field=models.CharField(blank=True, choices=[('', 'Any'), ('full_time', 'Full-time'), ('part_time', 'Part-time'), ('internship', 'Internship'), ('contract', 'Contract')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_location',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_remote',
            field=models.CharField(blank=True, choices=[('', 'Any'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
