# Generated by Django 4.2.28 on 2026-03-30 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_existing_profiles_verified(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    Profile.objects.all().update(email_verified=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_ensure_all_users_have_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailVerificationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('last_sent_at', models.DateTimeField()),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'email verification state',
                'verbose_name_plural': 'email verification states',
            },
        ),
        migrations.RunPython(set_existing_profiles_verified, noop_reverse),
    ]
