# Generated by Django 6.0.2 on 2026-02-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitid', models.BigIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=128)),
                ('state', models.CharField(blank=True, db_index=True, default='', max_length=2)),
                ('website_url', models.URLField(blank=True, default='')),
                ('institution_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('for_profit', 'For-profit')], db_index=True, default='public', max_length=20)),
                ('tuition_in', models.PositiveIntegerField(blank=True, help_text='Average cost of attendance or in-state tuition (annual)', null=True)),
                ('acceptance_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Admission rate 0-100', max_digits=5, null=True)),
                ('undergrad_count', models.PositiveIntegerField(blank=True, help_text='Undergraduate enrollment (for size: small <2k, medium 2k-15k, large 15k+)', null=True)),
                ('strong_majors', models.JSONField(blank=True, default=list, help_text='List of major keys matching career_quiz (e.g. computer_science, engineering)')),
                ('known_for', models.JSONField(blank=True, default=list, help_text="Raw CIPTITLE values from Scorecard (e.g. 'Computer Science')")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
