# Generated by Django 6.0.2 on 2026-02-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Campus image URL (e.g. from Wikipedia or school website)'),
        ),
    ]
